# This workflow will build a Java project with Maven and bundle them as native app installers with jDeploy
# See https://www.jdeploy.com for more information.

name: jDeploy CI with Maven

on:
  push:
    branches: ['*']
    tags: ['*']

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -Dmaven.test.skip=true dependency:copy-dependencies -DoutputDirectory=lib

      - name: Print contents (dist)
        run: ls -alh dist/

      - name: Print contents (lib)
        run: ls -alh lib/

      - name: Create TASSEL "Standalone" distribution
        run: |
          mkdir -p dist/tassel-5-standalone
          cp -r lib/ dist/tassel-5-standalone/
          cp dist/sTASSEL.jar dist/tassel-5-standalone/
          cp \
            *.pl \
            *.bat \
            dist/tassel-5-standalone/

      - name: Print contents (standalone)
        run: ls -alh dist/tassel-5-standalone/

      # - name: Build App Installer Bundles
      #   uses: shannah/jdeploy@master
      #   with:
      #     github_token: ${{ github.token }}
